<?php
/**
 * @file
 * Adds a jQuery plugin that sets the elements you specify to the same height.
 *
 * This module implements a jQuery plugin that can equalize the height of the
 * user specified elements with the same class.
 * By default, the height of the tallest element is used, but minimum and
 * maximum height can also be set.
 */

/**
 * Implements hook_help().
 */
function jquery_matchheight_help($path = '', $arg = NULL) {
  $output = '';
  switch ($path) {
    case 'admin/help#jquery_matchheight':
    case 'admin/config/development/jquery_matchheight':
      $output = '<p>' . t("Implements a jQuery plugin that makes the height of the elements equal.") . '</p>';
      $output .= t("Add elements or CSS classes that you need to be of equal height (with a leading period ('.') ) . <br />");
      $output .= t('Note: you can combine multiple selectors, i.e. "header, .wrapper".');
      $output .= t('You can optionally set minimum and maximum height, overflow value.&nbsp;');
      $output .= t('(<a href="@about">Read more about the plugin.</a>) ', array('@about' => 'http://brm.io/jquery-match-height-demo'));
      break;
  }
  return $output;
}

/**
 * Implements hook_library().
 *
 * For the file packaged with the module.
 */

 /* Prepare for deletion when libraries dependency is removed 

function jquery_matchheight_library() {
  $libraries['jquery-jquery_matchheight'] = array(
    'title' => "jQuery matchHeight",
    'website' => 'http://www.cssnewbie.com/jquery_matchheight-jquery-plugin/',
    'version' => '1.0',
    'js' => array(
      backdrop_get_path('module', 'jquery_matchheight') . '/jquery.jquery_matchheight.js' => array(),
    ),
  );
  return $libraries;
}
*/

/**
 * Implements hook_libraries_info().
 *
 * For defining external libraries.
 */
 
 /* Prepare for deletion when libraries dependency is removed 
   
function jquery_matchheight_libraries_info() {
  $libraries['imagesloaded'] = array(
    'name' => 'jquery imagesloaded',
    'vendor url' => 'https://github.com/desandro/imagesloaded',
    'download url' => 'https://github.com/desandro/imagesloaded',
    // 2.1.12
    'version arguments' => array(
      'file' => 'jquery.imagesloaded.js',
      'pattern' => '@plugin v([0-9\.a-z]+)@',
      'lines' => 5,

    ),
    'files' => array(
      'js' => array(
        'jquery.imagesloaded.min.js',
      ),
    ),
    'variants' => array(
      'minified' => array(
        'files' => array(
          'js' => array(
            'jquery.imagesloaded.min.js',
          ),
        ),
      ),
      'source' => array(
        'files' => array(
          'js' => array(
            'jquery.imagesloaded.js',
          ),
        ),
      ),
    ),
  );
  return $libraries;
}
*/

/**
 * Implements hook_menu().
 */
function jquery_matchheight_menu() {
  $description = t('Add CSS classes that you need to be of equal height, without a leading period (\'.\').<br />');
  $description .= t('You can optionally set minimum and maximum height, overflow value.&nbsp;');
  $description .= t('(<a href="@about">Read more about the plugin.</a>) ', array('@about' => 'http://www.cssnewbie.com/jquery_matchheight-jquery-plugin/'));

  $items = array();
  $items['admin/config/development/jquery_matchheight'] = array(
    'title' => 'jQuery matchHeight',
    'description' => 'Configure elements with equal heights.',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('jquery_matchheight_admin'),
    'file' => 'jquery_matchheight.admin.inc',
  );
  return $items;
}

/*
 * Implements hook_theme().
 */
function jquery_matchheight_theme() {
  return array(
    'jquery_matchheight_classes' => array(
      'render element' => 'form',
      'file' => 'jquery_matchheight.admin.inc',
    ),
  );
}

 /* Prepare for deletion when libraries dependency is removed 

function jquery_matchheight_load_libraries($jquery_matchheightclasses) {
  // Determine which variant of the script to load depending
  // on the config settings.
  $imagesloaded_ie8 = variable_get('jquery_matchheight_imagesloaded_iele8');
  $settings = array('classes' => $jquery_matchheightclasses,
                    'imagesloaded_ie8' => $imagesloaded_ie8);
  if (variable_get('jquery_matchheight_imagesloaded_min')) {
    $variant = 'minified';
  }
  else {
    $variant = 'source';
  }

  $library = libraries_load('imagesloaded', $variant);
  if ($library && !empty($library['loaded'])) {
    // Only load settings once.
    static $loaded = FALSE;
    if (!$loaded) {
      backdrop_add_js(array('equalHeightsModule' => $settings), 'setting');
      $loaded = TRUE;
    }
  }
  else {
    $message = t('The imagesloaded library was not found! Please following the instructions from the README.txt to get the plugin.');
    backdrop_set_message($message, $type = 'error');
  }
}

*/
